# -*- coding: utf-8 -*-
"""app_dash2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S98u8e07x9fMBqEyJbJOmshHQ-8_3ikM
"""

import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

df = pd.DataFrame({
    "reservationn_status": ["Checked-out", "Canceled", "No-show"],
    "deposite_type": ["No-deposite", "No-refund", "Refund"],
    "stays_in_week_nights": [1, 2,3],
})

fig = px.bar(df, x="deposite_type", y="stays_in_week_nights", color="stays_in_week_nights")

app.layout = html.Div(children=[
    html.H1(children='Hotel Booking Status'),

    html.Div(children='''
        Can Guest Predict Their Status Whether Checked-out Or Canceled?
    '''),

    dcc.Graph(
        id='example-graph',
        figure=fig
    )
])
   

 
if __name__ == '__main__':
    app.run_server(debug=True)